### configuration file for DMR workflow ###
root: "/home/msleeper" # path to root directory

### conditional configuration ###
# Alignment options (set to true if you want to run the alignment pathway)
# must set at least one of these to true to run the pipeline
bismark: True # set to true if you want the bismark processing pathway to run
bwameth: False # set to true if you want the bwameth processing pathway to run

### All directories will have the root path prepended to them later ###
# Do not include the root path in the config directories or files below

### data accession and metadata info tsv (can be freely changed) ###
samples_tsv: "workflows/DMReproducible/supplementary/402_test_data.tsv" 

### directories for outputs (can be freely changed) ###
genomes_dir: "scratch/genomes" # path to genome output directory
data_dir: "scratch/data" # path to data output directory 
reports_dir: "scratch/reports" # path to reports output directory

# ### reference genome information (can be changed with special consideration noted in comments) ###
ref:
  genome: "hg38" # genome build name (can be freely changed)
  fasta: "hg38.analysisSet" # prefix for genome fasta file name (this must match file name from goldenPath without the extentions)
  goldenPath: "//hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/analysisSet/hg38.analysisSet.fa.gz" # UCSC genome browser path to reference genome fasta file (can be freely changed)
  
  ### reference index directories ###
  wgbstools_idx_dir: "programs/wgbs_tools/references" # root dir will be appened onto this (only change beginning to match location of wgbs_tools program directory (wgbstools must be set up separately before running the pipeline - should end in "/wgbs_tools/references")

  ### annotation file info ###
  gtf: "hg38.knownGene" # prefix for gtf file name (must match file name from gtf_goldenPath without the extentions)
  gtf_goldenPath: "//hgdownload.soe.ucsc.edu/goldenPath/hg38/bigZips/genes/hg38.knownGene.gtf.gz" # UCSC genome browser path to gtf file (can be freely changed but file should end in gtf.gz)
  annotation_file: /home/msleeper/workflows/dmr_workflow/supplementary/gencode.v44.chr_patch_hapl_scaff.basic.annotation.gff3.gz

### additional arguments for pre-processing subworkflow rules ###
prep_args:
  rsync_get_ref: "-avzP --progress --ignore-existing" # rsync arguments
  bismark_genome_prep: "--verbose --bowtie2" # bismark arguments
  trim_galore_se: "--phred33" # trim_galore arguments (do not add --fastqc or -o as they are specified within the rule)
  # trim galore removed all reads for 318 files due to being trimmed below 20 bp length when using -q 67

# mosdepth:
#     threads : 4
#     mapping_quality : 10
