workingdir: "/home/msleeper/scratch/crc_dmr" # path to working directory

samples_tsv: "/home/msleeper/workflows/dmr_workflow/pipeline/data/318_test_data.tsv" # path to sample sheet

genomes_dir: "/home/msleeper/scratch/genomes" # path to genome directory
data_dir: "/home/msleeper/scratch/data" # path to data directory (raw sequencing files will be downloaded here within 'raw_sequence_files' directory)
reports_dir: "/home/msleeper/scratch/reports" # path to reports directory

ref:
  genome: "hg38" # genome build
  dir: "/home/msleeper/scratch/genomes/hg38/analysisSet" # path to genome directory (ref fasta will be downloaded here within here)
  fasta: "hg38.analysisSet" # prefix for genome fasta file name 
  goldenPath: "//hgdownload.cse.ucsc.edu/goldenPath/hg38/bigZips/analysisSet/hg38.analysisSet.fa.gz" # UCSC genome browser path to reference genome fasta file
  bismark_idx_dir: "/home/msleeper/scratch/genomes/hg38/analysisSet/bismark/Bisulfite_Genome" # Bismark output directory
  bwa_idx_dir: "/home/msleeper/scratch/genomes/hg38/analysisSet/bwameth" # bwameth output to same directory as input (this should match ref.dir)
  wgbstools_idx_dir: "/home/msleeper/programs/wgbs_tools/references" # wgbs_tools ref index output directory
  wgbstools_ref_name: "hg38_analysisSet" # wgbs_tools ref index name

data:
  dir: "/home/msleeper/scratch/data" # path to data directory

prep_args:
  rsync_get_ref: "-avzP --progress --ignore-existing" # rsync arguments
  bismark_genome_prep: "--verbose --bowtie2" # bismark arguments
  trim_galore_se: "--phred33" # trim_galore arguments (do not add --fastqc or -o as they are specified within the rule)
  # trim galore removed all reads for 318 files due to being trimmed below 20 bp length when using -q 67