

configfile: "config.yaml"

rule all:
     input: expand("{outdir}{fasta}", outdir = config["ref"]["outputdir"], fasta = config["ref"]["fasta"])

##### include rules #####
include:"rules/0_rsync_ref_genome.smk"