

configfile: "config.yaml"

rule all:
     input: expand("{outdir}/{fasta}.fa.gz", outdir = config["ref"]["dir"], fasta = config["ref"]["fasta"])

##### include rules #####
include:"rules/0_rsync_ref_genome.smk"
