

configfile: "config.yaml"

subworkflow prep:
     workdir: "/home/msleeper/workflows/dmr_workflow/pipeline/pre-processing" # path to pre-processing pipeline
     snakefile: "/home/msleeper/workflows/dmr_workflow/pipeline/pre-processing/prep-Snakefile" # path to pre-processing snakefile

# rule all:
#      input: expand("{outdir}/{fasta}.fa.gz", outdir = config["ref"]["dir"], fasta = config["ref"]["fasta"])

# ##### include rules #####
# include:"rules/0_rsync_get_ref_genome.smk"
# include:"rules/0_bwameth_idx_ref.smk"
# include:"rules/0_bismark_idx_ref.smk"

