rule reports:
    input:
        fastqc_pretrim_se = expand("{rep_dir}/fastqc/pre-trim/{{ref}}/{{patient_id}}/{{group}}-{{srx_id}}-{{layout}}/{{accession}}_fastqc.{suf}", rep_dir=config["reports_dir"], suf=["html","zip"]), # fastqc se output
        fastqc_pretrim_pe = expand("{rep_dir}/fastqc/pre-trim/{{ref}}/{{patient_id}}/{{group}}-{{srx_id}}-{{layout}}/{{accession}}_{read}_fastqc.{suf}", rep_dir=config["reports_dir"], read=["1", "2"], suf=["html", ".zip"]), # fastqc pe R1 and R2 output
        fastqc_posttrim_se = expand("{rep_dir}/fastqc/post-trim/{{ref}}/{{patient_id}}/{{group}}-{{srx_id}}-{{layout}}/{{accession}}_trimmed_fastqc.{suf}", rep_dir=config["reports_dir"], suf=["html","zip"]), # fastqc se post-trim output from trim_galore
        fastqc_posttrim_pe = expand("{rep_dir}/fastqc/post-trim/{{ref}}/{{patient_id}}/{{group}}-{{srx_id}}-{{layout}}/{{accession}}_{read}_trimmed_fastqc.{suf}", rep_dir=config["reports_dir"], read=["1", "2"], suf=["html", ".zip"]), # fastqc pe R1 and R2 post-trim output from trim_galore
        trim_report_se = expand("{rep_dir}/trim_galore/{{ref}}/{{patient_id}}/{{group}}-{{srx_id}}-{{layout}}/{{accession}}.fastq_trimming_report.txt", rep_dir=config["reports_dir"]), # trim_galore report se
        trim_report_pe = expand("{rep_dir}/trim_galore/{{ref}}/{{patient_id}}/{{group}}-{{srx_id}}-{{layout}}/{{accession}}_{read}.fastq_trimming_report.txt", rep_dir=config["reports_dir"], read=["1", "2"]), # trim_galore reports pe R1 and R2
        bwa_report = expand("{rep_dir}/bwameth/{{ref}}/{{patient_id}}/{{group}}-{{srx_id}}-{{layout}}/{{accession}}_trimmed_bwameth_report.txt", rep_dir=config["reports_dir"]),
        report = expand("{rep_dir}//bismark_bwt2/{{ref}}/{{patient_id}}/{{group}}-{{srx_id}}-{{layout}}/{{accession}}_trimmed_bismark_bt2_SE_report.txt", rep_dir=config["reports_dir"])